name: blogger
services:
  api:
    # becomes blogger-api
    build:
      context: ./BloggerApi/BloggerApi
    ports:
      - 8000:8080
    volumes:
      - ./BloggerApi/BloggerApi/Database:/BloggerApi/Database
  react:
    # becomes blogger-react
    build: ./blogger-react
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
